spring:
  datasource:
    url: jdbc:mysql://39.106.103.58:3307/ry-cloud?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT&autoReconnect=true&useSSL=false
    username: root
    password: cywhm521
    driverClassName: com.mysql.cj.jdbc.Driver
